name: 'Tencent SCF Action'
description: Github action for serverless framework
runs:
  using: 'composite'
  steps:
    - run: npm install -g serverless-cloud-framework
      shell: bash
    - run: scf deploy --debug
      shell: bash          
branding:
  icon: 'upload-cloud' 
  color: blue
